---
- name: Create directory and clone GIT repo (Cloned Amit repor)
  hosts: localhost
  become: true
  vars_files:
    - vault.yml
  vars:
    repo_url: "git@github.com:Anu-Raghavendran/linuxtraining.git"
    repo_dest: "/opt/clonerepo"
  tasks:
    - name: Ensure git us installed
      dnf:
        name: git
        state: present
    - name: Ensure repo directory exists
      file:
        path: "{{repo_dest}}"
        state: directory
        owner: "{{ ansible_user | default('student') }}"
        mode: '0755'
    - name: copy ssh key to target
      copy:
        src: ssh/id_rsa
        dest: /tmp/id_rsa
        mode: '0600'
    - name: clone repo using SSH key
      environment:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        force: yes


